version: '3'

services:
  database:
    image: 'mariadb:10.3'
    container_name: 'projeto-integrador-database'
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    healthcheck:
      test:
        [
          "mysql",
          "--user=root",
          "--password=${DB_PASSWORD}",
          "-e \"show databases;\""
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always

  api:
    image: takasaki.dev/projeto-integrador-api
    container_name: 'projeto-integrador-api'
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 127.0.0.1:4000:4000
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=jdbc:mysql://database:3306/${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - image-storage:/app/upload

volumes:
  database-data:
  image-storage:
